GstKalman: anonymous_namespace{gstkalman.cpp} Namespace Reference
anonymous_namespace{gstkalman.cpp} Namespace Reference
Classes
struct _GstKalman
The GStreamer Kalman filter video plugin element datastructure.
Typedefs
using kalman = fcarouge::kalman< float, float >
Enumerations
enum property : guint { _ , p , r }
The GStreamer Kalman filter element properties.
Functions
G_DEFINE_TYPE (GstKalman, gst_kalman, GST_TYPE_BASE_TRANSFORM)
auto initialize (GstPlugin *plugin) -> gboolean
Registers the plugin element.
void gst_kalman_set_property (GObject *object, guint prop_id, const GValue *value, GParamSpec *pspec)
Update the element instance data on property change.
void gst_kalman_get_property (GObject *object, guint prop_id, GValue *value, GParamSpec *pspec)
Provides the element instance data on property request.
auto gst_kalman_transform_in_place (GstBaseTransform *element_base, GstBuffer *output) -> GstFlowReturn
Processes the data buffer in-place.
GST_PLUGIN_DEFINE (GST_VERSION_MAJOR, GST_VERSION_MINOR, kalman, description.data(), initialize, version.data(), license.data(), name.data(), origin.data()) GST_ELEMENT_REGISTER_DEFINE(kalman
name data ()
name gst_kalman_get_type ())
void gst_kalman_class_init (GstKalmanClass *klass)
Defines the element details.
void gst_kalman_init (GstKalman *element)
Instantiates the element.
Variables
constexpr std::string_view name {"kalman"}
constexpr std::string_view classification {"Filter/Effect/Video"}
constexpr std::string_view long_name {"Kalman Filter"}
constexpr std::string_view description {"A video Kalman filter plugin."}
constexpr std::string_view version {"0.1.0"}
constexpr std::string_view license {"Unlicense"}
constexpr std::string_view author
constexpr std::string_view origin
constexpr std::string_view capabilities {"video/x-raw"}
name GST_RANK_NONE
Typedef Documentation
kalman
using anonymous_namespace{gstkalman.cpp}::kalman = typedef fcarouge::kalman<float, float>
Definition at line 58 of file gstkalman.cpp.
Enumeration Type Documentation
property
enum anonymous_namespace{gstkalman.cpp}::property : guint
The GStreamer Kalman filter element properties.
Todo:
Understand why GLib must have a zero-th property.
Enumerator
_
p
r
Definition at line 81 of file gstkalman.cpp.
: guint { _, p, r };
Function Documentation
data()
name anonymous_namespace{gstkalman.cpp}::data ()
G_DEFINE_TYPE()
anonymous_namespace{gstkalman.cpp}::G_DEFINE_TYPE (GstKalman , gst_kalman , GST_TYPE_BASE_TRANSFORM)
gst_kalman_class_init()
void anonymous_namespace{gstkalman.cpp}::gst_kalman_class_init (GstKalmanClass * klass)
Defines the element details.
Sets up the element metadata, static sink and source, in-place compute, and properties.
Definition at line 124 of file gstkalman.cpp.
{
  auto *object_klass{G_OBJECT_CLASS(klass)};
  object_klass->set_property = gst_kalman_set_property;
  object_klass->get_property = gst_kalman_get_property;
  constexpr GParamFlags described_readwrite{
      static_cast<GParamFlags>(static_cast<unsigned>(G_PARAM_READWRITE) |
                               static_cast<unsigned>(G_PARAM_STATIC_STRINGS))};
  constexpr auto max_float{std::numeric_limits<float>::max()};
  g_object_class_install_property(
      object_klass, property::p,
      g_param_spec_float("p", "P", "Initialize estimate uncertainty.", 0.,
                         max_float, 1., described_readwrite));
  g_object_class_install_property(
      object_klass, property::r,
      g_param_spec_float("r", "R", "Initialize output uncertainty.", 0.,
                         max_float, 0., described_readwrite));
  auto *gstelement_klass{GST_ELEMENT_CLASS(klass)};
  gst_element_class_set_static_metadata(gstelement_klass, long_name.data(),
                                        classification.data(),
                                        description.data(), author.data());
  GstStaticPadTemplate sink_template{"sink", GstPadDirection::GST_PAD_SINK,
                                     GstPadPresence::GST_PAD_ALWAYS,
                                     GST_STATIC_CAPS(capabilities.data())};
  gst_element_class_add_pad_template(
      gstelement_klass, gst_static_pad_template_get(&sink_template));
  GstStaticPadTemplate source_template{"src", GstPadDirection::GST_PAD_SRC,
                                       GstPadPresence::GST_PAD_ALWAYS,
                                       GST_STATIC_CAPS(capabilities.data())};
  gst_element_class_add_pad_template(
      gstelement_klass, gst_static_pad_template_get(&source_template));
  GST_BASE_TRANSFORM_CLASS(klass)->transform_ip =
      GST_DEBUG_FUNCPTR(gst_kalman_transform_in_place);
}
References author, capabilities, classification, description, gst_kalman_get_property(), gst_kalman_set_property(), gst_kalman_transform_in_place(), long_name, p, and r.
gst_kalman_get_property()
void anonymous_namespace gstkalman anonymous_namespace{gstkalman.cpp}::cpp::gst_kalman_get_property (GObject * object, guint prop_id, GValue * value, GParamSpec * pspec)
Provides the element instance data on property request.
Todo:
Implement and test.
Definition at line 184 of file gstkalman.cpp.
{
  static_cast<void>(object);
  static_cast<void>(prop_id);
  static_cast<void>(value);
  static_cast<void>(pspec);
}
Referenced by gst_kalman_class_init().
gst_kalman_get_type()
name anonymous_namespace{gstkalman.cpp}::gst_kalman_get_type ()
gst_kalman_init()
void anonymous_namespace{gstkalman.cpp}::gst_kalman_init (GstKalman * element)
Instantiates the element.
Nothing to do for now.
Definition at line 195 of file gstkalman.cpp.
{ static_cast<void>(element); }
gst_kalman_set_property()
void anonymous_namespace gstkalman anonymous_namespace{gstkalman.cpp}::cpp::gst_kalman_set_property (GObject * object, guint prop_id, const GValue * value, GParamSpec * pspec)
Update the element instance data on property change.
Definition at line 164 of file gstkalman.cpp.
{
  static_cast<void>(pspec);
  switch (auto *element{GST_KALMAN(object)}; prop_id) {
  case property::p:
    element->p = g_value_get_float(value);
    break;
  case property::r:
    element->r = g_value_get_float(value);
    break;
  default:
    G_OBJECT_WARN_INVALID_PROPERTY_ID(object, prop_id, pspec);
    break;
  }
}
References p, and r.
Referenced by gst_kalman_class_init().
gst_kalman_transform_in_place()
auto anonymous_namespace gstkalman anonymous_namespace{gstkalman.cpp}::cpp::gst_kalman_transform_in_place (GstBaseTransform * element_base, GstBuffer * output) -> GstFlowReturn
Processes the data buffer in-place.
Filters the frame pixels. Reset and reinitialize the filters on resolution change.
Todo:
Should the buffer be unmapped even on failed status?
Todo:
Support additional formats, hardwares, contexts, and strategies.
Todo:
Resolution is a poor indicator of the need to re-initialized the filters.
Todo:
Todo:
Should this check be performed as an event, signal, or capabilities change instead of part of the transform?
Todo:
Support in-place non-default construction to avoid the secondary initialization loop?
Todo:
Use the timestamp of the frame if available?
Todo:
Should the buffer be unmapped even on failed status?
Todo:
Support additional formats, hardwares, contexts, and strategies.
Todo:
Resolution is a poor indicator of the need to re-initialized the filters.
Todo:
Todo:
Should this check be performed as an event, signal, or capabilities change instead of part of the transform?
Todo:
Support in-place non-default construction to avoid the secondary initialization loop?
Todo:
Use the timestamp of the frame if available?
Definition at line 201 of file gstkalman.cpp.
{
  if (GST_CLOCK_TIME_IS_VALID(GST_BUFFER_TIMESTAMP(output))) {
    gst_object_sync_values(GST_OBJECT(element_base),
                           GST_BUFFER_TIMESTAMP(output));
  }
  const sr::unique_resource source_capabilities{
      gst_pad_get_current_caps(element_base->srcpad), gst_caps_unref};
  g_return_val_if_fail(source_capabilities.get(), GST_FLOW_ERROR);
  const auto *source_data{gst_caps_get_structure(source_capabilities.get(), 0)};
  g_return_val_if_fail(source_data, GST_FLOW_ERROR);
  gint width{0};
  g_return_val_if_fail(gst_structure_get_int(source_data, "width", &width),
                       GST_FLOW_ERROR);
  gint height{0};
  g_return_val_if_fail(gst_structure_get_int(source_data, "height", &height),
                       GST_FLOW_ERROR);
  auto *element{GST_KALMAN(element_base)};
  auto &filters{element->filters};
  const std::size_t resolution{static_cast<std::size_t>(width * height)};
  GstMapInfo map;
  const sr::unique_resource mapping{
      gst_buffer_map(output, &map, GST_MAP_READWRITE),
      [&map, &output](gboolean status) {
        static_cast<void>(status);
        gst_buffer_unmap(output, &map);
      }};
  const std::span pixels{map.data, resolution};
  if (resolution != filters.size()) {
    filters = std::vector<kalman>{resolution};
    std::transform(std::execution::par_unseq, std::begin(pixels),
                   std::end(pixels), std::begin(filters), std::begin(pixels),
                   [element](const auto &pixel, auto &filter) {
                     filter.x(static_cast<typename kalman::state>(pixel));
                     filter.p(element->p);
                     filter.r(element->r);
                     return pixel;
                   });
  } else {
    std::transform(std::execution::par_unseq, std::begin(pixels),
                   std::end(pixels), std::begin(filters), std::begin(pixels),
                   []<typename Pixel>(const Pixel &pixel, auto &filter) {
                     filter.update(static_cast<typename kalman::output>(pixel));
                     using limit = std::numeric_limits<Pixel>;
                     return std::clamp<Pixel>(filter.x(), limit::min(),
                                              limit::max());
                   });
  }
  return GST_FLOW_OK;
}
Referenced by gst_kalman_class_init().
GST_PLUGIN_DEFINE()
anonymous_namespace{gstkalman.cpp}::GST_PLUGIN_DEFINE (GST_VERSION_MAJOR , GST_VERSION_MINOR , kalman , description. data(), initialize , version. data(), license. data(), name. data(), origin. data())
initialize()
auto anonymous_namespace gstkalman anonymous_namespace{gstkalman.cpp}::cpp::initialize (GstPlugin * plugin) -> gboolean
Registers the plugin element.
Definition at line 116 of file gstkalman.cpp.
{
  return GST_ELEMENT_REGISTER(kalman, plugin);
}
Variable Documentation
author
constexpr std::string_view anonymous_namespace{gstkalman.cpp}::author constexpr
Initial value:
{
    "Francois Carouge <francois.carouge@gmail.com>"}
Definition at line 89 of file gstkalman.cpp.
Referenced by gst_kalman_class_init().
capabilities
constexpr std::string_view anonymous_namespace{gstkalman.cpp}::capabilities {"video/x-raw"} constexpr
Definition at line 93 of file gstkalman.cpp.
Referenced by gst_kalman_class_init().
classification
constexpr std::string_view anonymous_namespace{gstkalman.cpp}::classification {"Filter/Effect/Video"} constexpr
Definition at line 84 of file gstkalman.cpp.
Referenced by gst_kalman_class_init().
description
constexpr std::string_view anonymous_namespace{gstkalman.cpp}::description {"A video Kalman filter plugin."} constexpr
Definition at line 86 of file gstkalman.cpp.
Referenced by gst_kalman_class_init().
GST_RANK_NONE
name anonymous_namespace{gstkalman.cpp}::GST_RANK_NONE
Definition at line 112 of file gstkalman.cpp.
license
constexpr std::string_view anonymous_namespace{gstkalman.cpp}::license {"Unlicense"} constexpr
Definition at line 88 of file gstkalman.cpp.
long_name
constexpr std::string_view anonymous_namespace{gstkalman.cpp}::long_name {"Kalman Filter"} constexpr
Definition at line 85 of file gstkalman.cpp.
Referenced by gst_kalman_class_init().
name
constexpr std::string_view anonymous_namespace{gstkalman.cpp}::name {"kalman"} constexpr
Definition at line 83 of file gstkalman.cpp.
origin
constexpr std::string_view anonymous_namespace{gstkalman.cpp}::origin constexpr
Initial value:
{
    "https://github.com/FrancoisCarouge/GstKalman"}
Definition at line 91 of file gstkalman.cpp.
version
constexpr std::string_view anonymous_namespace{gstkalman.cpp}::version {"0.1.0"} constexpr
Definition at line 87 of file gstkalman.cpp.