name: "Install: Ubuntu 22.04 GCC"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Install
      # https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-14/+bug/1989124
      run: |
        sudo apt update
        sudo apt remove -y libunwind-14-dev
        sudo apt install \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libtbb2-dev
        ( cd /tmp
          git clone --depth 1 "https://github.com/catchorg/catch2"
          cmake -S "catch2" -B "catch2/build"
          cmake --build "catch2/build" --parallel 4
          sudo cmake --install "catch2/build" )
    - name: Build
      run: |
        cmake -B "build" .
        cmake --build "build" --parallel 4
        sudo cmake --install "build"
