name: "Test Memory: Valgrind"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Update
      run: sudo apt update
    - name: Install
      run: |
        sudo apt install gcc-12 g++-12 valgrind
    - name: Build
      run: |
        gcc-12 source/*.cpp -Iinclude \
          -g -O0 -std=c++23 -lstdc++
    - name: Test
      run: valgrind --verbose ./a.out
